# Auto-labeler configuration for PRs
# Labels are applied based on file paths
# Format for actions/labeler@v5

'area: auth':
  - changed-files:
      - any-glob-to-any-file:
          - 'src/app/core/auth/**/*'
          - 'src/app/features/auth/**/*'

'area: dashboard':
  - changed-files:
      - any-glob-to-any-file:
          - 'src/app/features/user/**/*'
          - 'src/app/features/admin/**/*'

'area: landing':
  - changed-files:
      - any-glob-to-any-file:
          - 'src/app/features/landing-page/**/*'

'area: shared':
  - changed-files:
      - any-glob-to-any-file:
          - 'src/app/shared/**/*'

'area: teams':
  - changed-files:
      - any-glob-to-any-file:
          - 'src/app/features/teams/**/*'

'area: payments':
  - changed-files:
      - any-glob-to-any-file:
          - 'src/app/features/payments/**/*'

'area: subscriptions':
  - changed-files:
      - any-glob-to-any-file:
          - 'src/app/features/subscription/**/*'

'area: documents':
  - changed-files:
      - any-glob-to-any-file:
          - 'src/app/features/documents/**/*'

'area: ocr':
  - changed-files:
      - any-glob-to-any-file:
          - 'src/app/features/ocr/**/*'

'type: documentation':
  - changed-files:
      - any-glob-to-any-file:
          - 'docs/**/*'
          - '**/*.md'

'type: tests':
  - changed-files:
      - any-glob-to-any-file:
          - '**/*.spec.ts'
          - '**/*.test.ts'

'type: styles':
  - changed-files:
      - any-glob-to-any-file:
          - '**/*.css'
          - '**/*.scss'

'type: config':
  - changed-files:
      - any-glob-to-any-file:
          - 'angular.json'
          - 'tsconfig*.json'
          - '.github/**/*'

'type: dependencies':
  - changed-files:
      - any-glob-to-any-file:
          - 'package.json'
          - 'pnpm-lock.yaml'

'priority: critical':
  - changed-files:
      - any-glob-to-any-file:
          - 'src/app/core/**/*'

'ui: components':
  - changed-files:
      - any-glob-to-any-file:
          - 'src/app/shared/ui/**/*'
          - 'src/app/shared/components/**/*'

